language: php

php:
  - 7.2

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

env:
    global:
        - COMPOSER_ARGS="--no-interaction"
        - COVERAGE_DEPS="php-coveralls/php-coveralls"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist $COMPOSER_ARGS
  - travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --colors=always --coverage-clover clover.xml

after_script:
    - travis_retry php vendor/bin/php-coveralls -v

notifications:
    email: false
